### PR TITLE
New CI/CD pipeline

### PR DESCRIPTION
**Pull request by hrosa**

### CODE REVIEW

**Comment by hrosa** [comment]
test comment

**Comment by hrosa** [comment]
test

**Comment by admincxs** [comment]
Closed%20by%20$CURRENT_COMMIT

**Comment by hrosa** [comment]
Closed%20by%20af0935a5297c126c3cf61e19467dbff2d5791185

**Comment by admincxs** [comment]
Closed by $COMMENT_DATA

**Comment by hrosa** [comment]
Closed%20by%20af0935a5297c126c3cf61e19467dbff2d5791185

**Comment by hrosa** [comment]
Closed by af0935a5297c126c3cf61e19467dbff2d5791185

**Comment by hrosa** [comment]
Closed%20by%20af0935a5297c126c3cf61e19467dbff2d5791185

**Comment by admincxs** [comment]
06cafe523536a0749ee7804fc06ec6ffd7d14bf3

**Comment by admincxs** [comment]
f5baf31ff31920378e60c987ad4eb8f75bae3c75

**Comment by admincxs** [comment]
802e096d908f1cae824a6342a995c6356aee285e

**Pull request closed without merging**
